### ISSUE TITLE
update to KDE runtime 5.15

### ISSUE THREAD

**Issue by eszlari** [flathub/com.notepadqq.Notepadqq#1]

**Comment by scx** [comment]
@eszlari 

The current stable release (_1.4.8_ - _2018-05-11_) uses **QtWebKit** as HTML engine.
When I was creating the manifest, there was no `io.qt.qtwebkit.BaseApp` for KDE 5.12 at all.
https://github.com/flathub/io.qt.qtwebkit.BaseApp/issues/12
Now we have it, but only for aarch64 and x86_64.
https://github.com/flathub/io.qt.qtwebkit.BaseApp/blob/3001f8d4a0c670610bc8b052cda102eb47bfa962/flathub.json#L3
Builds for arm and i386 are still missing due to a linker memory issue.
https://github.com/flathub/io.qt.qtwebkit.BaseApp/issues/14

The development version of Notepadqq has already replaced **QtWebKit** with **QtWebEngine**, so it doesn't need this BaseApp.
I have already created a branch for beta (_2018-09-14_):
https://github.com/scx/notepadqq-flatpak/tree/beta
Moreover, there is also another branch for the latest version (_2019-01-27_).
https://github.com/scx/notepadqq-flatpak/tree/qtwebengine
This one fixes the multiple instance problem.
https://github.com/notepadqq/notepadqq/issues/828#issuecomment-453922691

In the past, Flathub allowed only stable releases. However, it seems that this rule is no longer in use. I suggested switching to a newer version, but it remained unanswered, at least for now.
https://github.com/notepadqq/notepadqq/issues/828#issuecomment-458488964

**Comment by scx** [comment]
I just [created](https://github.com/flathub/com.notepadqq.Notepadqq/pull/5) the `beta` [branch](https://github.com/flathub/com.notepadqq.Notepadqq/tree/beta) for Notepadqq [2.0.0~beta](https://github.com/notepadqq/notepadqq/releases/tag/v2.0.0-beta) (QtWebEngine). It uses the KDE 5.12 runtime.

It should be available in the `flathub-beta` repository very soon (within 24 hours).

## Installation

### System wide

```
$ flatpak remote-add --if-not-exists "flathub-beta" "https://flathub.org/beta-repo/flathub-beta.flatpakrepo"
```

```
$ flatpak install "flathub-beta" "com.notepadqq.Notepadqq"
```

### Per user

```
$ flatpak remote-add --user --if-not-exists "flathub-beta" "https://flathub.org/beta-repo/flathub-beta.flatpakrepo"
```

```
$ flatpak install --user "flathub-beta" "com.notepadqq.Notepadqq"
```

## Launching

```
flatpak run --branch="beta" "com.notepadqq.Notepadqq"
```
or
```
$ flatpak run "com.notepadqq.Notepadqq//beta"
```

You can also change the default launcher in the menu to `beta`:
```
$ flatpak make-current "com.notepadqq.Notepadqq" "beta"
```

---

I also provided standalone packages:
https://github.com/scx/notepadqq-flatpak/releases

See also:
https://blogs.gnome.org/alexl/2019/02/19/changes-in-flathub-land/
https://github.com/flathub/flathub/wiki/App-Maintenance#the-repository

**Comment by scx** [comment]
Notepadqq `2.0.0~beta` (QtWebEngine, KDE _5.12_) is now available in the `beta` branch.
```
$ flatpak search notepadqq
Application ID          Version    Branch Remotes      Description            
com.notepadqq.Notepadqq 2.0.0~beta beta   flathub-beta An advanced text editor
com.notepadqq.Notepadqq 1.4.8      stable flathub      An advanced text editor
```
